
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
export const getStaticProps=async()=>{

    const {data}= await axios.get("https://jsonplaceholder.typicode.com/posts/");
    return {
        props: {
            data:data,
        }, // will be passed to the page component as props
      }

}
export default function Products({data}) {
 
   return <>
         <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"/>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
      </Head>
   
   {data.map((curElem)=>{
            return <div className="container-fluid"  key={curElem.id} >
            <div className="col-md-12 ">
                <Link href={`/blog/${curElem.id}`}><h2>{curElem.id}</h2></Link>
                <h2>{curElem.title} </h2>
            </div>
            </div>
            })};
        </>
   
  }
  
  